version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: dockerfile-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - safeway-test

  monitor:
    build:
      context: .
      dockerfile: dockerfile-monitor
    container_name: monitor
    ports:
      - "8081:8081"
    networks:
      - safeway-test

  eventos:
    build:
      context: .
      dockerfile: dockerfile-events
    container_name: eventos
    networks:
      - safeway-test

  usuarios:
    build: 
      context: .
      dockerfile: dockerfile-users
    container_name: usuarios
    networks:
      - safeway-test

  notificaciones:
    build: 
      context: .
      dockerfile: dockerfile-notification
    container_name: notificaciones
    networks:
      - safeway-test

  postgresql14-eventos:
    image: postgres:14
    container_name: postgres14-safeway-eventos
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres-eventos-atenea'
      POSTGRES_DB: 'safeway_events'
    networks:
      - safeway-test

  postgresql14-usuarios:
    image: postgres:14
    container_name: postgres14-safeway-usuarios
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres-usuarios-ares'
      POSTGRES_DB: 'safeway_users'
    networks:
      - safeway-test

  postgresql14-notificaciones:
    image: postgres:14
    container_name: postgres14-safeway-notificaciones
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres-notificaciones-poseidon'
      POSTGRES_DB: 'safeway_noti'
    networks:
      - safeway-test

networks:
  safeway-test:
    driver: bridge
