# Usa una imagen de Node.js como base
FROM node:18-alpine

# Establece el directorio de trabajo en /usr/src/app
WORKDIR /usr/src/app

# Copia el archivo package.json desde la ubicación adecuada
COPY package*.json ./
COPY tsconfig*.json ./


# Instala las dependencias de la aplicación
RUN npm install

# Copia el resto de la aplicación al directorio de trabajo
COPY ./apps/eventmonitor-msvc .

# Compila la aplicación (ajusta el comando según sea necesario)
RUN npm run build

# Expón el puerto 8080
EXPOSE 8081

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["npm", "start"]
